<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ieiet</name>
   <tag></tag>
   <elementGuidId>abffd4db-74fb-4ab8-bd26-0c030e181059</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Ieiet')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://secure.tvnet.lv/?return_to=https%3A%2F%2Fwww.tvnet.lv%2F&amp;_ga=2.15857011.473797679.1635762257-775030464.1635762257</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ieiet</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;theme-postimees device-desktop tvnet country-lv&quot;]/body[@class=&quot;section-4133 digipakett-branding-visible digipakett-branding-visible--new-account&quot;]/div[@class=&quot;root&quot;]/header[@class=&quot;site-header&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;site-header__top flex flex--align-items-center flex--justify-content-space-between&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;menu-items menu-items--top&quot;]/div[@class=&quot;login-menu&quot;]/div[@class=&quot;user-menu hidden-sections modal&quot;]/div[@class=&quot;user-menu__top flex flex--align-items-center flex--justify-content-center&quot;]/a[@class=&quot;button&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ieiet')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ieiet'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUS'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Izveidot kontu >'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://secure.tvnet.lv/?return_to=https%3A%2F%2Fwww.tvnet.lv%2F&amp;_ga=2.15857011.473797679.1635762257-775030464.1635762257')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/a</value>
   </webElementXpaths>
</WebElementEntity>
